GET  http://localhost:1113/identity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsX25hbWUiOiJJc2FpYWggMjIyIiwicGFzc3BvcnRfbnVtYmVyIjoiUE4xMTEyMjIiLCJpYXQiOjE3MzIzNzcwMzksImV4cCI6MTczMjM3NzA1OX0.Pgcxv5ExXp8TIYGnFxnXhOr1CMBPwaB1khaybxJtZAM




###

POST /login HTTP/1.1
HOST:localhost:2111
Content-Type: application/json

{
  "passport_number":  "PN111222"
}

###
POST /register HTTP/1.1
Host: localhost:2111
Content-Type: application/json

{
  "full_name":"Isaiah 222",
  "passport_number": "PN111222"
}